services:
  ace-hls:
    build: .
    container_name: ace_hls_viewer
    restart: unless-stopped
    ports:
      - "${ACE_HLS_PORT}:5000"
    volumes:
      - ace_hls_data:/app/data
    networks:
      - ace_hls_stream
    # devices:
    #   - /dev/dri:/dev/dri
    environment:
      - ACEXY_IP=${ACEXY_IP}
      - ACEXY_PORT=${ACEXY_PORT}
      - CACHE_DURATION=${CACHE_DURATION}
      - PLAYLIST_REFRESH_INTERVAL=${PLAYLIST_REFRESH_INTERVAL:-900}
      - FFMPEG_RW_TIMEOUT=${FFMPEG_RW_TIMEOUT:-60}
      - HLS_IDLE_TIMEOUT=${HLS_IDLE_TIMEOUT:-120}
      - URL_ORIGEN=${URL_ORIGEN}
      - ENABLE_TRANSCODE=${ENABLE_TRANSCODE:-false}
      - ORCHESTRATOR_URL=${ORCHESTRATOR_URL:-}
      - ORCHESTRATOR_API_PREFIX=${ORCHESTRATOR_API_PREFIX:-/api/v1}
      - ORCHESTRATOR_API_TOKEN=${ORCHESTRATOR_API_TOKEN:-defaultpassword}
      - ORCHESTRATOR_TIMEOUT=${ORCHESTRATOR_TIMEOUT:-5}

  acestream:
    image: martinbjeldbak/acestream-http-proxy:latest
    container_name: acestream
    restart: unless-stopped
    networks:
      - ace_hls_stream

  acexy:
    image: ghcr.io/javinator9889/acexy:0.2.2
    container_name: acexy
    restart: unless-stopped
    ports:
      - "${ACEXY_PORT}:${ACEXY_PORT}"
    environment:
      ACEXY_LISTEN_ADDR: ":${ACEXY_PORT}"
      ACEXY_SCHEME: "${ACEXY_SCHEME}"
      ACEXY_HOST: "${ACEXY_HOST}"
      ACEXY_PORT: "${ACESTREAM_PORT}"
      ACEXY_M3U8_STREAM_TIMEOUT: "${ACEXY_M3U8_STREAM_TIMEOUT}"
      ACEXY_M3U8: "${ACEXY_M3U8}"
      ACEXY_EMPTY_TIMEOUT: "${ACEXY_EMPTY_TIMEOUT}"
      ACEXY_BUFFER_SIZE: "${ACEXY_BUFFER_SIZE}"
      ACEXY_NO_RESPONSE_TIMEOUT: "${ACEXY_NO_RESPONSE_TIMEOUT}"
    depends_on:
      - acestream
    networks:
      - ace_hls_stream

volumes:
  ace_hls_data:


networks:
  ace_hls_stream:
    name: ace_hls_stream
